import random

# List of top 500 US cities with their state abbreviations
us_cities_with_states = [
    ("New York", "NY"), ("Los Angeles", "CA"), ("Chicago", "IL"), ("Houston", "TX"), 
    ("Phoenix", "AZ"), ("Philadelphia", "PA"), ("San Antonio", "TX"), ("San Diego", "CA"), 
    ("Dallas", "TX"), ("San Jose", "CA"), ("Austin", "TX"), ("Jacksonville", "FL"), 
    ("San Francisco", "CA"), ("Columbus", "OH"), ("Indianapolis", "IN"), ("Fort Worth", "TX"), 
    ("Charlotte", "NC"), ("Seattle", "WA"), ("Denver", "CO"), ("El Paso", "TX"), 
    ("Detroit", "MI"), ("Boston", "MA"), ("Memphis", "TN"), ("Nashville", "TN"), 
    ("Baltimore", "MD"), ("Oklahoma City", "OK"), ("Las Vegas", "NV"), ("Louisville", "KY"), 
    ("Milwaukee", "WI"), ("Albuquerque", "NM"), ("Tucson", "AZ"), ("Fresno", "CA"), 
    ("Sacramento", "CA"), ("Kansas City", "MO"), ("Mesa", "AZ"), ("Atlanta", "GA"), 
    ("Colorado Springs", "CO"), ("Omaha", "NE"), ("Raleigh", "NC"), ("Miami", "FL"), 
    ("Cleveland", "OH"), ("Tulsa", "OK"), ("Oakland", "CA"), ("Minneapolis", "MN"), 
    ("Wichita", "KS"), ("Arlington", "TX"), ("Bakersfield", "CA"), ("Tampa", "FL"), 
    ("Aurora", "CO"), ("Honolulu", "HI"), ("Anaheim", "CA"), ("Santa Ana", "CA"), 
    ("St. Louis", "MO"), ("Riverside", "CA"), ("Corpus Christi", "TX"), ("Lexington", "KY"), 
    ("Stockton", "CA"), ("Henderson", "NV"), ("Saint Paul", "MN"), ("Cincinnati", "OH"), 
    ("Pittsburgh", "PA"), ("Greensboro", "NC"), ("Anchorage", "AK"), ("Plano", "TX"), 
    ("Lincoln", "NE"), ("Orlando", "FL"), ("Irvine", "CA"), ("Newark", "NJ"), 
    ("Toledo", "OH"), ("Chula Vista", "CA"), ("Jersey City", "NJ"), ("Durham", "NC"), 
    ("Madison", "WI"), ("Laredo", "TX"), ("Chandler", "AZ"), ("Buffalo", "NY"), 
    ("Lubbock", "TX"), ("Scottsdale", "AZ"), ("Reno", "NV"), ("Glendale", "AZ"), 
    ("Norfolk", "VA"), ("Winston-Salem", "NC"), ("North Las Vegas", "NV"), 
    ("Gilbert", "AZ"), ("Hialeah", "FL"), ("Garland", "TX"), ("Boise", "ID"), 
    ("Baton Rouge", "LA"), ("Richmond", "VA"), ("Des Moines", "IA"), ("Shreveport", "LA"), 
    ("Aurora", "IL"), ("Montgomery", "AL"), ("Akron", "OH"), ("Little Rock", "AR"), 
    ("Tempe", "AZ"), ("Columbia", "SC"), ("Fargo", "ND"), ("Birmingham", "AL"), 
    ("Peoria", "IL"), ("Akron", "OH"), ("Salt Lake City", "UT"), ("Providence", "RI"), 
    ("Newport News", "VA"), ("Brownsville", "TX"), ("Overland Park", "KS"), 
    ("Grand Prairie", "TX"), ("Cape Coral", "FL"), ("Jackson", "MS"), ("McKinney", "TX"), 
    ("Killeen", "TX"), ("Augusta", "GA"), ("Frisco", "TX"), ("Mobile", "AL"), 
    ("Macon", "GA"), ("El Monte", "CA"), ("Grand Rapids", "MI"), ("Wilmington", "DE"), 
    ("Waco", "TX"), ("Cedar Rapids", "IA"), ("Odessa", "TX"), ("Syracuse", "NY"), 
    ("Huntsville", "AL"), ("Salt Lake City", "UT"), ("Lafayette", "LA"), ("Boulder", "CO"), 
    ("Lawton", "OK"), ("Canton", "OH"), ("Green Bay", "WI"), ("Fargo", "ND"), 
    ("Santa Clara", "CA"), ("Pueblo", "CO"), ("League City", "TX"), ("Springfield", "IL"), 
    ("Peoria", "IL"), ("Gresham", "OR"), ("Elgin", "IL"), ("St. Charles", "IL"), 
    ("Tempe", "AZ"), ("Palm Bay", "FL"), ("Round Rock", "TX"), ("West Palm Beach", "FL"), 
    ("Columbus", "OH"), ("Greensboro", "NC"), ("Newport News", "VA"), ("Richardson", "TX"), 
    ("Cedar Rapids", "IA"), ("Waterbury", "CT"), ("Youngstown", "OH"), ("Chattanooga", "TN"), 
    ("Jacksonville", "FL"), ("Macon", "GA"), ("Akron", "OH"), ("Provo", "UT"), 
    ("Eugene", "OR"), ("Bend", "OR"), ("Billings", "MT"), ("Kalamazoo", "MI"), 
    ("Lafayette", "LA"), ("Salisbury", "MD"), ("Decatur", "IL"), ("Madison", "WI"), 
    ("El Paso", "TX"), ("Cheyenne", "WY"), ("Des Moines", "IA"), ("Traverse City", "MI"), 
    ("Battle Creek", "MI"), ("Hattiesburg", "MS"), ("Pittsfield", "MA"), ("Jackson", "MS"), 
    ("Huntington", "WV"), ("Champaign", "IL"), ("Hickory", "NC"), ("Peoria", "IL"), 
    ("Gainesville", "FL"), ("Murray", "KY"), ("Knoxville", "TN"), ("Palm Coast", "FL"), 
    ("Columbus", "OH"), ("Mount Pleasant", "MI"), ("Dothan", "AL"), ("Syracuse", "NY"), 
    ("Cleveland", "OH"), ("Plattsburgh", "NY"), ("Chattanooga", "TN"), ("Gulfport", "MS"), 
    ("Huntsville", "AL"), ("Jacksonville", "FL"), ("Pensacola", "FL"), ("Beaumont", "TX"), 
    ("Pocatello", "ID"), ("La Crosse", "WI"), ("Harrisonburg", "VA"), ("Cedar City", "UT"), 
    ("Moore", "OK"), ("Lewiston", "ID"), ("Glendale", "AZ"), ("Killeen", "TX"), 
    ("Greenville", "SC"), ("Harrisonburg", "VA"), ("Pocatello", "ID"), ("Bozeman", "MT"), 
    ("Mason City", "IA"), ("Culpeper", "VA"), ("Boulder", "CO"), ("Vicksburg", "MS"), 
    ("Gadsden", "AL"), ("Waco", "TX"), ("Iowa City", "IA"), ("Lynchburg", "VA"), 
    ("Eugene", "OR"), ("Fort Smith", "AR"), ("Alpena", "MI"), ("Dubuque", "IA"), 
    ("Amarillo", "TX"), ("Rapid City", "SD"), ("St. George", "UT"), ("Coos Bay", "OR"), 
    ("Pueblo", "CO"), ("Sheridan", "WY"), ("Harrisonburg", "VA"), ("La Grande", "OR"), 
    ("Shreveport", "LA"), ("Sherman", "TX"), ("Grand Island", "NE"), ("Greenwood", "MS"), 
    ("Muskegon", "MI"), ("Cheyenne", "WY"), ("Joplin", "MO"), ("Eagle Pass", "TX"), 
    ("Newport News", "VA"), ("Cedar Rapids", "IA"), ("Montgomery", "AL"), ("Bismarck", "ND"), 
    ("Cleburne", "TX"), ("Pottstown", "PA"), ("Alamosa", "CO"), ("Murray", "KY"), 
    ("Winter Haven", "FL"), ("Dothan", "AL"), ("Macon", "GA"), ("Decatur", "IL"), 
    ("Huntsville", "AL"), ("Odessa", "TX"), ("Burlington", "VT"), ("Pocatello", "ID"), 
    ("McAllen", "TX"), ("Athens", "GA"), ("Muskogee", "OK"), ("Hobbs", "NM"), 
    ("San Angelo", "TX"), ("Starkville", "MS"), ("Aberdeen", "SD"), ("Missoula", "MT"), 
    ("Bismarck", "ND"), ("Moorhead", "MN"), ("Champaign", "IL"), ("Bartlesville", "OK"), 
    ("Carrollton", "TX"), ("Williamsport", "PA"), ("Auburn", "AL"), ("Oshkosh", "WI"), 
    ("Jasper", "AL"), ("Cleveland", "OH"), ("Elyria", "OH"), ("Alpena", "MI"), 
    ("Hickory", "NC"), ("Richmond", "VA"), ("Waterloo", "IA"), ("Saginaw", "MI"), 
    ("Wichita Falls", "TX"), ("Evansville", "IN"), ("Pine Bluff", "AR"), ("Starkville", "MS"), 
    ("Greenville", "MS"), ("Big Spring", "TX"), ("Fort Dodge", "IA"), ("El Centro", "CA"), 
    ("Twin Falls", "ID"), ("Baxter", "MN"), ("Red Wing", "MN"), ("Duluth", "MN"), 
    ("Minot", "ND"), ("St. Cloud", "MN"), ("Pocatello", "ID"), ("Painesville", "OH"), 
    ("Brownwood", "TX"), ("Watertown", "SD"), ("Wenatchee", "WA"), ("Pittsfield", "MA"), 
    ("Aberdeen", "SD"), ("Joplin", "MO"), ("Yankton", "SD"), ("Sioux Falls", "SD"), 
    ("Wenatchee", "WA"), ("Alamogordo", "NM"), ("Bainbridge", "GA"), ("Pueblo", "CO"), 
    ("Salina", "KS"), ("Sanford", "FL"), ("Blair", "NE"), ("Gadsden", "AL"), 
    ("Boulder", "CO"), ("Missoula", "MT"), ("Jacksonville", "FL"), ("Mason City", "IA"), 
    ("La Grande", "OR"), ("Rock Springs", "WY"), ("Walla Walla", "WA"), 
    ("Lewiston", "ID"), ("Port Angeles", "WA"), ("Ketchikan", "AK"), 
    ("Nacogdoches", "TX"), ("Columbus", "OH"), ("Sallisaw", "OK"), 
    ("Morgantown", "WV"), ("Winona", "MN"), ("Othello", "WA"), 
    ("Aberdeen", "SD"), ("Gulfport", "MS"), ("Gainesville", "FL"), 
    ("Dothan", "AL"), ("Waco", "TX"), ("Burlington", "VT"), 
    ("Grand Forks", "ND"), ("La Porte", "TX"), ("Muskogee", "OK"), 
    ("North Platte", "NE"), ("Colorado Springs", "CO"), 
    ("Georgetown", "TX"), ("Vicksburg", "MS"), ("Kingman", "AZ"), 
    ("Valdosta", "GA"), ("Laramie", "WY"), ("Dothan", "AL"), 
    ("Bryan", "TX"), ("Bozeman", "MT"), ("Salinas", "CA"), 
    ("Sanford", "FL"), ("Carson City", "NV"), ("Grand Forks", "ND"), 
    ("Elk City", "OK"), ("Rochester", "NY"), ("Wichita Falls", "TX"), 
    ("Richland", "WA"), ("Harlingen", "TX"), ("Gainesville", "FL"), 
    ("Jackson", "MS"), ("Burlington", "VT"), ("Meridian", "MS"), 
    ("South Bend", "IN"), ("Centralia", "WA"), ("Harrisonburg", "VA"), 
    ("Wenatchee", "WA"), ("Waco", "TX"), ("Barstow", "CA"), 
    ("Portsmouth", "VA"), ("Grants Pass", "OR"), ("Santa Cruz", "CA"), 
    ("Auburn", "AL"), ("Turlock", "CA"), ("Binghamton", "NY"), 
    ("Hanford", "CA"), ("La Crosse", "WI"), ("Bainbridge", "GA"), 
    ("Muskogee", "OK"), ("North Platte", "NE"), ("Colorado Springs", "CO"), 
    ("Georgetown", "TX"), ("Vicksburg", "MS"), ("Kingman", "AZ"), 
    ("Valdosta", "GA"), ("Laramie", "WY"), ("Dothan", "AL"), 
    ("Bryan", "TX"), ("Bozeman", "MT"), ("Salinas", "CA"), 
    ("Sanford", "FL"), ("Carson City", "NV"), ("Grand Forks", "ND"), 
    ("Elk City", "OK"), ("Rochester", "NY"), ("Wichita Falls", "TX"), 
    ("Richland", "WA"), ("Harlingen", "TX"), ("Gainesville", "FL"), 
    ("Jackson", "MS"), ("Burlington", "VT"), ("Meridian", "MS"), 
    ("South Bend", "IN"), ("Centralia", "WA"), ("Harrisonburg", "VA"), 
    ("Wenatchee", "WA"), ("Waco", "TX"), ("Barstow", "CA"), 
    ("Portsmouth", "VA"), ("Grants Pass", "OR"), ("Santa Cruz", "CA")
]

def select_random_city_with_state(cities_list):
    # Ensure the list is not empty
    if not cities_list:
        raise ValueError("The cities list is empty")
    # Randomly select a city and state from the list
    return random.choice(cities_list)

# Example usage
selected_city, state_abbreviation = select_random_city_with_state(us_cities_with_states)
print(f"Randomly selected city: {selected_city}, {state_abbreviation}")
